name: Optimized Jekyll Deploy to Aliyun OSS

on:
  push:
    branches:
      - main

env:
  JEKYLL_ENV: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: lab-website-template-main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: lab-website-template-main

      - name: Build Site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Setup Aliyun OSS Utility
        uses: manyuanrong/setup-ossutil@v3.0
        with:
          endpoint: oss-cn-beijing.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Sync to Aliyun OSS
        run: |
          ossutil cp -rf ./lab-website-template-main/_site/ oss://digital-agriculture-team-lab/